// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddToCart(ctx context.Context, arg AddToCartParams) (CartItem, error)
	ClearCart(ctx context.Context, userID uuid.UUID) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteShop(ctx context.Context, id uuid.UUID) error
	GetCartItems(ctx context.Context, userID uuid.UUID) ([]GetCartItemsRow, error)
	GetCategory(ctx context.Context, id uuid.UUID) (Category, error)
	GetOrder(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsRow, error)
	GetOrdersByUser(ctx context.Context, userID uuid.UUID) ([]Order, error)
	GetProduct(ctx context.Context, id uuid.UUID) (Product, error)
	GetShop(ctx context.Context, id uuid.UUID) (Shop, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error)
	ListProductsByShop(ctx context.Context, shopID uuid.UUID) ([]Product, error)
	ListShops(ctx context.Context, arg ListShopsParams) ([]Shop, error)
	ListShopsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Shop, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveFromCart(ctx context.Context, arg RemoveFromCartParams) error
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	UpdateCartQuantity(ctx context.Context, arg UpdateCartQuantityParams) (CartItem, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
	UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
