FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/server/main.go

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/main .
COPY db/migration ./db/migration
COPY wait-for.sh .
COPY start.sh .

RUN chmod +x wait-for.sh
RUN chmod +x start.sh

EXPOSE 8000

CMD ["/app/main"]
